### ISSUE TITLE
cannot import name xlmain

### ISSUE THREAD

**Issue by ZJYCP** [xiaoland/xiaolan#1]
pi@raspberrypi:~/xiaolan $ python xldo.py
Traceback (most recent call last):
  File "xldo.py", line 19, in <module>
    import snowboy
  File "/home/pi/xiaolan/snowboy.py", line 11, in <module>
    import xldo
  File "/home/pi/xiaolan/xldo.py", line 20, in <module>
    import speaker
  File "/home/pi/xiaolan/speaker.py", line 8, in <module>
    from xldo import xlmain
ImportError: cannot import name xlmain

请问这是我个人的问题吗？？

**Comment by xiaoland** [comment]
哦，不是的
你用新的，这个老了，
再git clone一遍新的
记住要把xiaolan放在/home/pi下面

**Comment by xiaoland** [comment]
我已经更新了，你可以看看，有什么问题再告诉我，我会修改的

**Comment by KivenDa** [comment]
我怎样可以认识您呢？我也对交互机器人很感兴趣

**Comment by yulimfish** [comment]
偷偷摸摸滴说:README里有作者QQ！

**Comment by xiaoland** [comment]
关闭
